name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Packages
        run: npm install

      - name: Chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          build: npm run build:dev
          start: npm run start
          browser: chrome
  cypress-run-edge:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Packages
        run: npm install

      - name: Edge
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          build: npm run build:dev
          start: npm run start
          browser: edge
